name: Release Senior Thesis Proposal
on:
  push:
    tags:
      - '*.*.*'    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install pandoc
        uses: nikeee/setup-pandoc@v1
      - name: Install pandoc-citeproc
        run: sudo apt-get -qq update && sudo apt-get install -y pandoc-citeproc
      - name: Install tectonic
        uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up git repository
        uses: actions/checkout@v2
      - name: Resize images
        run: bash resize.sh
      - name: Convert with pandoc
        run: mkdir log && mkdir output && pandoc --defaults pdf.yaml --to latex --metadata-file config.yaml --lua-filter .filters/abstract-to-meta.lua --template template/proposal.tex
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload released asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: output/SeniorThesisProposal.pdf
          asset_name: SeniorThesisProposal.pdf
          asset_content_type: pdf
